[env:knob]
platform = espressif32@6.6.0
board = esp32-s3-devkitc-1
framework = arduino
board_build.flash_mode = qio
board_build.flash_size = 16MB
board_build.psram_type = opi
board_build.arduino.memory_type = qio_opi
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216
upload_port = COM9
monitor_port = COM9
monitor_speed = 115200
build_flags =
  -D BOARD_HAS_PSRAM
  -D ARDUINO_USB_CDC_ON_BOOT=1
  -D ARDUINO_USB_MODE=1
  -D LV_CONF_SKIP=1
  -D LV_COLOR_DEPTH=16
  -D LV_COLOR_16_SWAP=1
  -D LV_TICK_CUSTOM=1
  -D "LV_TICK_CUSTOM_INCLUDE=\"Arduino.h\""
  -D "LV_TICK_CUSTOM_SYS_TIME_EXPR=(millis())"
  -D LV_FONT_MONTSERRAT_14=1
  -D LV_FONT_MONTSERRAT_24=1
  -D LV_FONT_MONTSERRAT_48=1
  -D LV_USE_LOG=0
  -D LV_USE_SYSMON=0
  -D LV_USE_PERF_MONITOR=0
  -D LV_USE_MEM_MONITOR=0
  -D LV_USE_OBSERVER=1
  -D LV_USE_ASSERT_NULL=0
  -D LV_USE_ASSERT_MALLOC=0
  -D LV_USE_ASSERT_OBJ=0
  -D LV_USE_ASSERT_STYLE=0
lib_deps =
  lvgl/lvgl@~9.2.0
  bblanchon/ArduinoJson@^7
